-- DO NOT EDIT THIS FILE!  This file was generated by tools/GenerateMMLCombinators.hs.

{-# LANGUAGE OverloadedStrings #-}
module Text.YuruMath.Builder.MathML3.Attributes where
import Prelude ()
import Text.Blaze.Internal (Attribute, AttributeValue, attribute)

accent :: AttributeValue -> Attribute
accent = attribute "accent" " accent=\""

accentunder :: AttributeValue -> Attribute
accentunder = attribute "accentunder" " accentunder=\""

actiontype :: AttributeValue -> Attribute
actiontype = attribute "actiontype" " actiontype=\""

align :: AttributeValue -> Attribute
align = attribute "align" " align=\""

alignmentscope :: AttributeValue -> Attribute
alignmentscope = attribute "alignmentscope" " alignmentscope=\""

alt :: AttributeValue -> Attribute
alt = attribute "alt" " alt=\""

altimg :: AttributeValue -> Attribute
altimg = attribute "altimg" " altimg=\""

altimgHeight :: AttributeValue -> Attribute
altimgHeight = attribute "altimg-height" " altimg-height=\""

altimgValign :: AttributeValue -> Attribute
altimgValign = attribute "altimg-valign" " altimg-valign=\""

altimgWidth :: AttributeValue -> Attribute
altimgWidth = attribute "altimg-width" " altimg-width=\""

alttext :: AttributeValue -> Attribute
alttext = attribute "alttext" " alttext=\""

bevelled :: AttributeValue -> Attribute
bevelled = attribute "bevelled" " bevelled=\""

cd :: AttributeValue -> Attribute
cd = attribute "cd" " cd=\""

cdgroup :: AttributeValue -> Attribute
cdgroup = attribute "cdgroup" " cdgroup=\""

charalign :: AttributeValue -> Attribute
charalign = attribute "charalign" " charalign=\""

charspacing :: AttributeValue -> Attribute
charspacing = attribute "charspacing" " charspacing=\""

class_ :: AttributeValue -> Attribute
class_ = attribute "class" " class=\""

close :: AttributeValue -> Attribute
close = attribute "close" " close=\""

columnalign :: AttributeValue -> Attribute
columnalign = attribute "columnalign" " columnalign=\""

columnlines :: AttributeValue -> Attribute
columnlines = attribute "columnlines" " columnlines=\""

columnspacing :: AttributeValue -> Attribute
columnspacing = attribute "columnspacing" " columnspacing=\""

columnspan :: AttributeValue -> Attribute
columnspan = attribute "columnspan" " columnspan=\""

columnwidth :: AttributeValue -> Attribute
columnwidth = attribute "columnwidth" " columnwidth=\""

crossout :: AttributeValue -> Attribute
crossout = attribute "crossout" " crossout=\""

decimalpoint :: AttributeValue -> Attribute
decimalpoint = attribute "decimalpoint" " decimalpoint=\""

definitionURL :: AttributeValue -> Attribute
definitionURL = attribute "definitionURL" " definitionURL=\""

denomalign :: AttributeValue -> Attribute
denomalign = attribute "denomalign" " denomalign=\""

depth :: AttributeValue -> Attribute
depth = attribute "depth" " depth=\""

dir :: AttributeValue -> Attribute
dir = attribute "dir" " dir=\""

display :: AttributeValue -> Attribute
display = attribute "display" " display=\""

displaystyle :: AttributeValue -> Attribute
displaystyle = attribute "displaystyle" " displaystyle=\""

edge :: AttributeValue -> Attribute
edge = attribute "edge" " edge=\""

encoding :: AttributeValue -> Attribute
encoding = attribute "encoding" " encoding=\""

equalcolumns :: AttributeValue -> Attribute
equalcolumns = attribute "equalcolumns" " equalcolumns=\""

equalrows :: AttributeValue -> Attribute
equalrows = attribute "equalrows" " equalrows=\""

fence :: AttributeValue -> Attribute
fence = attribute "fence" " fence=\""

form :: AttributeValue -> Attribute
form = attribute "form" " form=\""

frame :: AttributeValue -> Attribute
frame = attribute "frame" " frame=\""

framespacing :: AttributeValue -> Attribute
framespacing = attribute "framespacing" " framespacing=\""

groupalign :: AttributeValue -> Attribute
groupalign = attribute "groupalign" " groupalign=\""

height :: AttributeValue -> Attribute
height = attribute "height" " height=\""

href :: AttributeValue -> Attribute
href = attribute "href" " href=\""

id :: AttributeValue -> Attribute
id = attribute "id" " id=\""

indentalign :: AttributeValue -> Attribute
indentalign = attribute "indentalign" " indentalign=\""

indentalignfirst :: AttributeValue -> Attribute
indentalignfirst = attribute "indentalignfirst" " indentalignfirst=\""

indentalignlast :: AttributeValue -> Attribute
indentalignlast = attribute "indentalignlast" " indentalignlast=\""

indentshift :: AttributeValue -> Attribute
indentshift = attribute "indentshift" " indentshift=\""

indentshiftfirst :: AttributeValue -> Attribute
indentshiftfirst = attribute "indentshiftfirst" " indentshiftfirst=\""

indentshiftlast :: AttributeValue -> Attribute
indentshiftlast = attribute "indentshiftlast" " indentshiftlast=\""

indenttarget :: AttributeValue -> Attribute
indenttarget = attribute "indenttarget" " indenttarget=\""

infixlinebreakstyle :: AttributeValue -> Attribute
infixlinebreakstyle = attribute "infixlinebreakstyle" " infixlinebreakstyle=\""

largeop :: AttributeValue -> Attribute
largeop = attribute "largeop" " largeop=\""

leftoverhang :: AttributeValue -> Attribute
leftoverhang = attribute "leftoverhang" " leftoverhang=\""

length :: AttributeValue -> Attribute
length = attribute "length" " length=\""

linebreak :: AttributeValue -> Attribute
linebreak = attribute "linebreak" " linebreak=\""

linebreakmultchar :: AttributeValue -> Attribute
linebreakmultchar = attribute "linebreakmultchar" " linebreakmultchar=\""

linebreakstyle :: AttributeValue -> Attribute
linebreakstyle = attribute "linebreakstyle" " linebreakstyle=\""

lineleading :: AttributeValue -> Attribute
lineleading = attribute "lineleading" " lineleading=\""

linethickness :: AttributeValue -> Attribute
linethickness = attribute "linethickness" " linethickness=\""

location :: AttributeValue -> Attribute
location = attribute "location" " location=\""

longdivstyle :: AttributeValue -> Attribute
longdivstyle = attribute "longdivstyle" " longdivstyle=\""

lquote :: AttributeValue -> Attribute
lquote = attribute "lquote" " lquote=\""

lspace :: AttributeValue -> Attribute
lspace = attribute "lspace" " lspace=\""

mathbackground :: AttributeValue -> Attribute
mathbackground = attribute "mathbackground" " mathbackground=\""

mathcolor :: AttributeValue -> Attribute
mathcolor = attribute "mathcolor" " mathcolor=\""

mathsize :: AttributeValue -> Attribute
mathsize = attribute "mathsize" " mathsize=\""

mathvariant :: AttributeValue -> Attribute
mathvariant = attribute "mathvariant" " mathvariant=\""

maxsize :: AttributeValue -> Attribute
maxsize = attribute "maxsize" " maxsize=\""

maxwidth :: AttributeValue -> Attribute
maxwidth = attribute "maxwidth" " maxwidth=\""

minlabelspacing :: AttributeValue -> Attribute
minlabelspacing = attribute "minlabelspacing" " minlabelspacing=\""

minsize :: AttributeValue -> Attribute
minsize = attribute "minsize" " minsize=\""

movablelimits :: AttributeValue -> Attribute
movablelimits = attribute "movablelimits" " movablelimits=\""

mslinethickness :: AttributeValue -> Attribute
mslinethickness = attribute "mslinethickness" " mslinethickness=\""

name :: AttributeValue -> Attribute
name = attribute "name" " name=\""

notation :: AttributeValue -> Attribute
notation = attribute "notation" " notation=\""

numalign :: AttributeValue -> Attribute
numalign = attribute "numalign" " numalign=\""

open :: AttributeValue -> Attribute
open = attribute "open" " open=\""

overflow :: AttributeValue -> Attribute
overflow = attribute "overflow" " overflow=\""

position :: AttributeValue -> Attribute
position = attribute "position" " position=\""

rightoverhang :: AttributeValue -> Attribute
rightoverhang = attribute "rightoverhang" " rightoverhang=\""

rowalign :: AttributeValue -> Attribute
rowalign = attribute "rowalign" " rowalign=\""

rowlines :: AttributeValue -> Attribute
rowlines = attribute "rowlines" " rowlines=\""

rowspacing :: AttributeValue -> Attribute
rowspacing = attribute "rowspacing" " rowspacing=\""

rowspan :: AttributeValue -> Attribute
rowspan = attribute "rowspan" " rowspan=\""

rquote :: AttributeValue -> Attribute
rquote = attribute "rquote" " rquote=\""

rspace :: AttributeValue -> Attribute
rspace = attribute "rspace" " rspace=\""

scriptlevel :: AttributeValue -> Attribute
scriptlevel = attribute "scriptlevel" " scriptlevel=\""

scriptminsize :: AttributeValue -> Attribute
scriptminsize = attribute "scriptminsize" " scriptminsize=\""

scriptsizemultiplier :: AttributeValue -> Attribute
scriptsizemultiplier = attribute "scriptsizemultiplier" " scriptsizemultiplier=\""

selection :: AttributeValue -> Attribute
selection = attribute "selection" " selection=\""

separator :: AttributeValue -> Attribute
separator = attribute "separator" " separator=\""

separators :: AttributeValue -> Attribute
separators = attribute "separators" " separators=\""

shift :: AttributeValue -> Attribute
shift = attribute "shift" " shift=\""

side :: AttributeValue -> Attribute
side = attribute "side" " side=\""

src :: AttributeValue -> Attribute
src = attribute "src" " src=\""

stackalign :: AttributeValue -> Attribute
stackalign = attribute "stackalign" " stackalign=\""

stretchy :: AttributeValue -> Attribute
stretchy = attribute "stretchy" " stretchy=\""

style :: AttributeValue -> Attribute
style = attribute "style" " style=\""

subscriptshift :: AttributeValue -> Attribute
subscriptshift = attribute "subscriptshift" " subscriptshift=\""

superscriptshift :: AttributeValue -> Attribute
superscriptshift = attribute "superscriptshift" " superscriptshift=\""

symmetric :: AttributeValue -> Attribute
symmetric = attribute "symmetric" " symmetric=\""

valign :: AttributeValue -> Attribute
valign = attribute "valign" " valign=\""

voffset :: AttributeValue -> Attribute
voffset = attribute "voffset" " voffset=\""

width :: AttributeValue -> Attribute
width = attribute "width" " width=\""

xref :: AttributeValue -> Attribute
xref = attribute "xref" " xref=\""
