-- DO NOT EDIT THIS FILE!  This file was generated by tools/GenerateMMLCombinators.hs.

{-# LANGUAGE OverloadedStrings #-}
module Text.YuruMath.Builder.MathML3
  (module Text.Blaze
  ,MathML
  ,toMathML
  ,annotation
  ,annotationXml
  ,maction
  ,maligngroup
  ,malignmark
  ,math
  ,menclose
  ,merror
  ,mfenced
  ,mfrac
  ,mglyph
  ,mi
  ,mlabeledtr
  ,mlongdiv
  ,mmultiscripts
  ,mn
  ,mo
  ,mover
  ,mpadded
  ,mphantom
  ,mprescripts
  ,mroot
  ,mrow
  ,ms
  ,mscarries
  ,mscarry
  ,msgroup
  ,msline
  ,mspace
  ,msqrt
  ,msrow
  ,mstack
  ,mstyle
  ,msub
  ,msubsup
  ,msup
  ,mtable
  ,mtd
  ,mtext
  ,mtr
  ,munder
  ,munderover
  ,none
  ,semantics
  ) where
import Text.Blaze
import Text.Blaze.Internal

type MathML = Markup

toMathML :: ToMarkup a => a -> MathML
toMathML = toMarkup

annotation :: MathML -> MathML
annotation = Parent "annotation" "<annotation" "</annotation>"

annotationXml :: MathML -> MathML
annotationXml = Parent "annotation-xml" "<annotation-xml" "</annotation-xml>"

maction :: MathML -> MathML
maction = Parent "maction" "<maction" "</maction>"

maligngroup :: MathML
maligngroup = Leaf "maligngroup" "<maligngroup" " />" ()

malignmark :: MathML
malignmark = Leaf "malignmark" "<malignmark" " />" ()

math :: MathML -> MathML
math = Parent "math" "<math" "</math>"

menclose :: MathML -> MathML
menclose = Parent "menclose" "<menclose" "</menclose>"

merror :: MathML -> MathML
merror = Parent "merror" "<merror" "</merror>"

mfenced :: MathML -> MathML
mfenced = Parent "mfenced" "<mfenced" "</mfenced>"

mfrac :: MathML -> MathML
mfrac = Parent "mfrac" "<mfrac" "</mfrac>"

mglyph :: MathML
mglyph = Leaf "mglyph" "<mglyph" " />" ()

mi :: MathML -> MathML
mi = Parent "mi" "<mi" "</mi>"

mlabeledtr :: MathML -> MathML
mlabeledtr = Parent "mlabeledtr" "<mlabeledtr" "</mlabeledtr>"

mlongdiv :: MathML -> MathML
mlongdiv = Parent "mlongdiv" "<mlongdiv" "</mlongdiv>"

mmultiscripts :: MathML -> MathML
mmultiscripts = Parent "mmultiscripts" "<mmultiscripts" "</mmultiscripts>"

mn :: MathML -> MathML
mn = Parent "mn" "<mn" "</mn>"

mo :: MathML -> MathML
mo = Parent "mo" "<mo" "</mo>"

mover :: MathML -> MathML
mover = Parent "mover" "<mover" "</mover>"

mpadded :: MathML -> MathML
mpadded = Parent "mpadded" "<mpadded" "</mpadded>"

mphantom :: MathML -> MathML
mphantom = Parent "mphantom" "<mphantom" "</mphantom>"

mprescripts :: MathML
mprescripts = Leaf "mprescripts" "<mprescripts" " />" ()

mroot :: MathML -> MathML
mroot = Parent "mroot" "<mroot" "</mroot>"

mrow :: MathML -> MathML
mrow = Parent "mrow" "<mrow" "</mrow>"

ms :: MathML -> MathML
ms = Parent "ms" "<ms" "</ms>"

mscarries :: MathML -> MathML
mscarries = Parent "mscarries" "<mscarries" "</mscarries>"

mscarry :: MathML -> MathML
mscarry = Parent "mscarry" "<mscarry" "</mscarry>"

msgroup :: MathML -> MathML
msgroup = Parent "msgroup" "<msgroup" "</msgroup>"

msline :: MathML
msline = Leaf "msline" "<msline" " />" ()

mspace :: MathML
mspace = Leaf "mspace" "<mspace" " />" ()

msqrt :: MathML -> MathML
msqrt = Parent "msqrt" "<msqrt" "</msqrt>"

msrow :: MathML -> MathML
msrow = Parent "msrow" "<msrow" "</msrow>"

mstack :: MathML -> MathML
mstack = Parent "mstack" "<mstack" "</mstack>"

mstyle :: MathML -> MathML
mstyle = Parent "mstyle" "<mstyle" "</mstyle>"

msub :: MathML -> MathML
msub = Parent "msub" "<msub" "</msub>"

msubsup :: MathML -> MathML
msubsup = Parent "msubsup" "<msubsup" "</msubsup>"

msup :: MathML -> MathML
msup = Parent "msup" "<msup" "</msup>"

mtable :: MathML -> MathML
mtable = Parent "mtable" "<mtable" "</mtable>"

mtd :: MathML -> MathML
mtd = Parent "mtd" "<mtd" "</mtd>"

mtext :: MathML -> MathML
mtext = Parent "mtext" "<mtext" "</mtext>"

mtr :: MathML -> MathML
mtr = Parent "mtr" "<mtr" "</mtr>"

munder :: MathML -> MathML
munder = Parent "munder" "<munder" "</munder>"

munderover :: MathML -> MathML
munderover = Parent "munderover" "<munderover" "</munderover>"

none :: MathML
none = Leaf "none" "<none" " />" ()

semantics :: MathML -> MathML
semantics = Parent "semantics" "<semantics" "</semantics>"
